## Machine Learning - Linear Regression - With scaler

In [1]:
import pandas as pd

# Data Pre-Processing

In [2]:
# Load Data 

df = pd.read_csv('Resources/summer_athlete_medals_count.csv')

df.head(3)

# country_df = df

# Filtering for USA
country_df = df[df['Country'] == 'USA']

In [3]:
# #  Filter for the following countries below:
# # 'USA', 'Russia', 'Germany', 'UK', 'France', 'Italy', 'China',
# # 'Australia', 'Sweden', 'Hungary', 'Japan', 'Finlad', 'Canada',
# # 'Romania', 'Netherlands', 'Poland', 'South Korea', 'Bulgaria',
# # 'Cuba', 'Denmark', 'Switzerland', 'Czech Repbulic', 'Belgium',
# # 'Norway', 'Greece'

# countries_25 = ['USA', 'Russia', 'Germany', 'UK', 'France', 'Italy', 'China',
# 'Australia', 'Sweden', 'Hungary', 'Japan', 'Finlad', 'Canada',
# 'Romania', 'Netherlands', 'Poland', 'South Korea', 'Bulgaria',
# 'Cuba', 'Denmark', 'Switzerland', 'Czech Repbulic', 'Belgium',
# 'Norway', 'Greece']

# country_df = df[df.Country.isin(countries_25)]
# country_df.head(3)

In [4]:
#  Ceate test data
test_data = country_df[country_df['Year'] > 2012]
test_data = pd.DataFrame(test_data)

# Dropping Total Medal count to prep for predictions
# test_data = test_data.drop(["Total_Medals","Gold","Silver","Bronze"], axis=1)
# test_data = test_data.drop(["Medals"], axis=1)


# Adding 2020 to prep for future prediction after hyperparameter tuning and training
new_row = pd.Series(data={'Year':2020, 'Country':'USA', 'Athletes':0, 
                          'Host':0, 'Sports':0, 'Events':0, 'Gold':0,'Silver':0, 'Bronze':0}, name='0')
test_data = test_data.append(new_row, ignore_index=False)
# test_data

#  Save into a csv file
test_data.to_csv('Resources/test.csv', index=False)

In [5]:
#  Create train data
train_data = country_df[country_df['Year'] <= 2012]
train_data = pd.DataFrame(train_data)
train_data
#  Save into a csv file
# train_data.to_csv('Resources/train.csv', index=False)

,Year,Country,Host,Athletes,Sports,Events,Gold,Silver,Bronze,Medals
1,1896,USA,0,14,3,16,11,6,2,19
13,1900,USA,0,75,10,41,21,16,17,54
43,1904,USA,1,524,18,95,76,79,75,230
60,1906,USA,0,38,5,28,12,5,6,23
78,1908,USA,0,122,10,52,22,12,12,46
100,1912,USA,0,174,11,68,26,18,19,63
128,1920,USA,0,288,18,113,41,27,27,95
157,1924,USA,0,299,18,108,45,27,27,99
202,1928,USA,0,280,15,96,22,18,16,56
248,1932,USA,1,474,17,122,44,36,30,110
296,1936,USA,0,359,21,127,24,21,12,57
344,1948,USA,0,300,19,126,38,27,19,84
403,1952,USA,0,286,18,133,40,19,17,76
471,1956,USA,0,305,19,144,32,25,17,74
542,1960,USA,0,292,17,147,34,21,16,71
625,1964,USA,0,346,19,159,36,26,28,90
717,1968,USA,0,357,18,167,45,28,34,107
830,1972,USA,0,400,21,185,33,31,30,94
950,1976,USA,0,396,19,189,34,35,25,94
1119,1984,USA,1,522,25,217,82,61,30,173
1260,1988,USA,0,527,27,230,36,31,27,94
1415,1992,USA,0,545,28,248,37,34,37,108
1582,1996,USA,1,648,31,263,44,32,25,101
1778,2000,USA,0,586,31,265,36,24,31,91
1977,2004,USA,0,533,31,254,36,39,26,101
2177,2008,USA,0,588,32,258,36,39,35,110
2380,2012,USA,0,529,31,245,46,28,29,103

In [6]:
#  View what columns actually exist
train_data.columns

Index(['Year', 'Country', 'Host', 'Athletes', 'Sports', 'Events', 'Gold',
       'Silver', 'Bronze', 'Medals'],
      dtype='object')

In [7]:
# Assign X and y for test and training data
y_train_medals = train_data["Medals"]
y_train_gold = train_data["Gold"]
y_train_silver = train_data["Silver"]
y_train_bronze = train_data["Bronze"]

X_train_features = train_data[['Year', 'Host', 'Athletes', 'Sports', 'Events']]
X_train = X_train_features.values


X_test_features = test_data[['Year','Host', 'Athletes', 'Sports', 'Events']]
X_test = X_test_features.values

In [8]:
# Setting X_train for scaling for year only 
X_train = X_train_features.Year
X_train = X_train.values.reshape(-1, 1)
X_train.shape

(27, 1)

In [9]:
# Transform the training and testing data using the X_scaler

# QUESTION: SCALING FOR YEAR

from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)


X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_test_features_scaled = X_scaler.transform(X_train_features)

ValueError: could not convert string to float: 'USA'

# Create and Train(Fit) Model

In [ ]:
 # Create a LinearRegression model and fit it to the training data

from sklearn.linear_model import LinearRegression
model_medals = LinearRegression()
model_medals.fit(X_train_scaled, y_train_medals)

model_gold = LinearRegression()
model_gold.fit(X_train_scaled, y_train_gold)

model_silver = LinearRegression()
model_silver.fit(X_train_scaled, y_train_silver)

model_bronze = LinearRegression()
model_bronze.fit(X_train_scaled, y_train_bronze)

In [10]:
print(f"Training Data Score for Medals: {model_medals.score(X_train_scaled, y_train_medals)}")
print(f"Training Data Score for Gold: {model_gold.score(X_train_scaled, y_train_gold)}")
print(f"Training Data Score for Silver: {model_silver.score(X_train_scaled, y_train_silver)}")
print(f"Training Data Score for Bronze: {model_bronze.score(X_train_scaled, y_train_bronze)}")

NameError: name 'model_medals' is not defined

# Hyperparameter Tuning - Ordinary Least Squares

In [16]:
# Source Link: https://www.datarobot.com/blog/ordinary-least-squares-in-python/
# Source Link: https://heartbeat.fritz.ai/implementing-ordinary-least-squares-ols-using-statsmodels-in-python-b1f4dee09419


import statsmodels.api as sm
import numpy as np

ols = sm.OLS(y_train_medals, X_test_features_scaled).fit()

ols_gold = sm.OLS(y_train_gold, X_test_features_scaled).fit()
ols_silver = sm.OLS(y_train_silver, X_test_features_scaled).fit()
ols_bronze = sm.OLS(y_train_bronze, X_test_features_scaled).fit()

In [17]:
# model_details = ols.summary()
# print("Model Summary for Medals")
# print(model_details)

# model_details_gold = ols_gold.summary()
# print("Model Summary for Gold")
# print(model_details_gold)

# model_details_silver = ols_silver.summary()
# print("Model Summary for Silver")
# print(model_details_silver)

# model_details_bronze = ols_bronze.summary()
# print("Model Summary for Bronze")
# print(model_details_bronze)


# R squared scores - from Model Summary
# print("R squared score for Medals: 0.666")

# print("R squared score for Gold: 0.598")

# print("R squared score for Silver: 0.657")

# print("R squared score for Bronze: 0.658")

R squared score for Medals: 0.666
R squared score for Gold: 0.598
R squared score for Silver: 0.657
R squared score for Bronze: 0.658

# Make Predictions

In [51]:
# # Make predictions with model
# predictions = model.predict(X_test_scaled)

# Make predictions with the hypertuned model
predictions = ols.predict(X_test_scaled)

predictions_gold = ols_gold.predict(X_test_scaled)
predictions_silver = ols_silver.predict(X_test_scaled)
predictions_bronze = ols_bronze.predict(X_test_scaled)

In [52]:
# Predicting - all

output_medals = pd.DataFrame({'Year': test_data.Year, 'Country': test_data.Country, 'Medals Predictions': predictions})
# output_medals

In [53]:
# Predicting - gold

output_gold = pd.DataFrame({'Year': test_data.Year, 'Country': test_data.Country, 'Gold Predictions': predictions_gold})
# output_gold

In [54]:
# Predicting - silver

output_silver = pd.DataFrame({'Year': test_data.Year, 'Country': test_data.Country, 'Silver Predictions': predictions_silver})
# output_silver

In [55]:
# Predicting - bronze

output_bronze = pd.DataFrame({'Year': test_data.Year, 'Country': test_data.Country, 'Bronze Predictions': predictions_bronze})
# output_bronze

# Prediction table

In [56]:
# Combining Medals, Gold, Silver, Bronze Predictions

combined_predictions_df = pd.DataFrame({'Year': test_data.Year, 'Country': test_data.Country, 'Host':test_data.Host,
                                        'Athletes': test_data.Athletes, 'Sports': test_data.Sports, 'Events': test_data.Events,
                                        'Gold': test_data.Gold, 'Silver': test_data.Silver, 'Bronze': test_data.Bronze, 'Medals': test_data.Medals,
                                        'Gold Predictions': predictions_gold.round(), 'Silver Predictions': predictions_silver.round(),
                                        'Bronze Predictions': predictions_bronze.round(), 'Medals Predictions': predictions.round()})

combined_predictions_df

,Year,Country,Host,Athletes,Sports,Events,Gold,Silver,Bronze,Medals,Gold Predictions,Silver Predictions,Bronze Predictions,Medals Predictions
2584,2016,USA,0,555,33,245,46,37,38,121.0,8.0,5.0,-0.0,13.0
0,2020,USA,0,0,0,0,0,0,0,NaN,-6.0,-16.0,-37.0,-58.0

In [57]:
#  Predicting for certain year

year_predictions_df = combined_predictions_df[combined_predictions_df['Year'] == 2016]
year_predictions_df

,Year,Country,Host,Athletes,Sports,Events,Gold,Silver,Bronze,Medals,Gold Predictions,Silver Predictions,Bronze Predictions,Medals Predictions
2584,2016,USA,0,555,33,245,46,37,38,121.0,8.0,5.0,-0.0,13.0